# Generated by Django 3.0.6 on 2020-06-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_chapter', models.FileField(blank=True, null=True, upload_to='chapters/%Y/%m/$D/')),
            ],
        ),
        migrations.AlterField(
            model_name='records',
            name='date_of_receipt',
            field=models.CharField(max_length=4, verbose_name='Год поступления'),
        ),
        migrations.AlterField(
            model_name='records',
            name='date_of_release',
            field=models.CharField(max_length=4, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='records',
            name='direction_of_study',
            field=models.CharField(max_length=50, verbose_name='Направление обучения'),
        ),
        migrations.AlterField(
            model_name='records',
            name='e_mail',
            field=models.CharField(max_length=25, verbose_name='Email'),
        ),
    ]
