# Generated by Django 3.0.6 on 2020-06-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200621_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sample_chapter',
            field=models.FileField(blank=True, null=True, upload_to='images/%Y/%m/%D/'),
        ),
    ]
