# Generated by Django 3.0.6 on 2020-06-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200621_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagesz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%D/')),
            ],
        ),
        migrations.DeleteModel(
            name='ASU_IMGS',
        ),
    ]
