# Generated by Django 3.0.6 on 2020-06-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200621_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesz',
            name='images',
        ),
        migrations.AddField(
            model_name='imagesz',
            name='image',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%D/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagesz',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
