# Generated by Django 3.0.6 on 2020-06-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_imagesz_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesz',
            options={'verbose_name': 'фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterField(
            model_name='imagesz',
            name='image',
            field=models.ImageField(upload_to='photos/', verbose_name='Изображение'),
        ),
    ]
